version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: das-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - das-network

  postgres:
    image: postgres:15
    container_name: das-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - das-network

  bot:
    build: .
    container_name: das-bot
    restart: always
    env_file:
      - .env
    environment:
      # Override DB and Redis hosts to use service names from docker-compose
      DB_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      - redis
      - postgres
    ports:
      # Expose the web server port for webhook testing
      - "8080:8080"
    networks:
      - das-network

volumes:
  redis_data:
  postgres_data:

networks:
  das-network:
    driver: bridge